stages:
  - build
  - deploy

cache:
    paths:
    - ./node_modules

build_job:
 image: node:12-alpine
 stage: build
 before_script:
        - echo "Installing NPM Dependencies and running angular application"
 script:
  - whoami
  - npm install
# http-server to serve files, gzipper to compress them after build

  - npm install
  - ng build --prod --output-hashing none
  - pwd

 artifacts:
  paths:
    - dist/

deploy_job:
  image: google/cloud-sdk:alpine
  stage: deploy
  only:
    - master
  dependencies:
    - build_job
  before_script:
  - "ServiceName=vrpd-frontend"
  - "echo $ServiceName"
  - |
    cat <<EOF >> app.yaml
    runtime: python27
    service: $ServiceName
    api_version: 1
    threadsafe: true
    handlers:
    - url: /(.+\.js)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.js)

    - url: /(.+\.css)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.css)

    - url: /(.+\.png)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.png)

    - url: /(.+\.jpg)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.jpg)

    - url: /(.+\.svg)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.svg)

    - url: /favicon.ico
      static_files: dist/VirtualReality/favicon.ico
      upload: dist/VirtualReality/favicon.ico

    - url: /(.+\.json)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.json)

    - url: /(.+\.gltf)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.gltf)

    - url: /(.+\.ttf)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.ttf)

    - url: /(.+\.woff)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.woff)

    - url: /(.+\.eot)
      static_files: dist/VirtualReality/\1
      upload: dist/VirtualReality/(.+\.eot)

    - url: /(.+)
      static_files: dist/VirtualReality/index.html
      upload: dist/VirtualReality/index.html

    - url: /
      static_files: dist/VirtualReality/index.html
      upload: dist/VirtualReality/index.html

    skip_files:
      - e2e/
      - node_modules/
      - src/
      - ^(./)?\..$
      - ^(./)?.\.json$
      - ^(./)?.\.md$
      - ^(./)?.\.yaml$
      - ^LICENSE
      - .git/objects
    EOF
  - "cat app.yaml"
  - echo $SERVICE_ACCOUNT > ${CI_PIPELINE_ID}.json
  script:
  - gcloud auth activate-service-account --key-file $CI_PIPELINE_ID.json
  - gcloud --project hu18-groupa-angular app deploy --version v2
  - url=$(gcloud app services browse $ServiceName --no-launch-browser --project hu18-groupa-angular)
  - echo $url
  after_script:
  - rm $CI_PIPELINE_ID.json
