stages:
  - build_angular


cache:
    paths:
    - ./node_modules

generate_artifact:
 image: node:12-alpine
 stage: build_angular
 before_script: 
        - echo "Installing NPM Dependencies and running angular application"
 only:
 - master
 script:
#  - npm install -g @angular/cli
  - whoami
  - npm install
  - npm install -g http-server
  - npm run build
  - nohup http-server ./dist/VirtualReality --port 8080 -a 0.0.0.0 </dev/null &>/dev/null &
#  - nohup ng serve --host 0.0.0.0 </dev/null &>/dev/null &
# obtain public IP
  - wget -qO- https://ipecho.net/plain ; echo
 artifacts:
  paths:
    - dist/

